name: refract

services:
  frontend:
    container_name: refract-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        VITE_DEFAULT_REDIRECT_URL: ${VITE_DEFAULT_REDIRECT_URL:-http://localhost:4000}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PORT: 3000
    depends_on:
      api:
        condition: service_started

  api:
    container_name: refract-api
    build:
      context: ./api
      dockerfile: Dockerfile.api
      target: api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8080}
      REDIRECTOR_PORT: ${REDIRECTOR_PORT:-8080}
      JWKS_URL: ${JWKS_URL:-http://frontend:3000/api/auth/jwks}
      DEFAULT_BASE_URL: ${DEFAULT_BASE_URL:-localhost:4000}
      VALKEY_HOST: ${VALKEY_HOST:-valkey}
      VALKEY_PORT: ${VALKEY_PORT:-6379}
      VALKEY_REDIRECT_KEY: ${VALKEY_REDIRECT_KEY:-redirect:{short_code}}
      VALKEY_CLICKS_STREAM_KEY: ${VALKEY_CLICKS_STREAM_KEY:-stream:clicks}
      VALKEY_READ_GROUP: ${VALKEY_READ_GROUP:-clicks_stream_group}
      VALKEY_CONSUMER: ${VALKEY_CONSUMER:-clicks_stream_consumer_1}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  redirector:
    container_name: refract-redirector
    build:
      context: ./api
      dockerfile: Dockerfile.redirector
      target: redirector
    ports:
      - "4000:8080"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8080}
      REDIRECTOR_PORT: ${REDIRECTOR_PORT:-8080}
      JWKS_URL: ${JWKS_URL:-http://frontend:3000/api/auth/jwks}
      DEFAULT_BASE_URL: ${DEFAULT_BASE_URL:-localhost:4000}
      VALKEY_HOST: ${VALKEY_HOST:-valkey}
      VALKEY_PORT: ${VALKEY_PORT:-6379}
      VALKEY_REDIRECT_KEY: ${VALKEY_REDIRECT_KEY:-redirect:{short_code}}
      VALKEY_CLICKS_STREAM_KEY: ${VALKEY_CLICKS_STREAM_KEY:-stream:clicks}
      VALKEY_READ_GROUP: ${VALKEY_READ_GROUP:-clicks_stream_group}
      VALKEY_CONSUMER: ${VALKEY_CONSUMER:-clicks_stream_consumer_1}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  worker:
    container_name: refract-worker
    build:
      context: ./api
      dockerfile: Dockerfile.worker
      target: worker
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8080}
      REDIRECTOR_PORT: ${REDIRECTOR_PORT:-8080}
      JWKS_URL: ${JWKS_URL:-http://frontend:3000/api/auth/jwks}
      DEFAULT_BASE_URL: ${DEFAULT_BASE_URL:-localhost:4000}
      VALKEY_HOST: ${VALKEY_HOST:-valkey}
      VALKEY_PORT: ${VALKEY_PORT:-6379}
      VALKEY_REDIRECT_KEY: ${VALKEY_REDIRECT_KEY:-redirect:{short_code}}
      VALKEY_CLICKS_STREAM_KEY: ${VALKEY_CLICKS_STREAM_KEY:-stream:clicks}
      VALKEY_READ_GROUP: ${VALKEY_READ_GROUP:-clicks_stream_group}
      VALKEY_CONSUMER: ${VALKEY_CONSUMER:-clicks_stream_consumer_1}
    depends_on:
      valkey:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    container_name: refract-postgres
    image: postgres:18-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    container_name: refract-valkey
    image: valkey/valkey-bundle:9-alpine
    environment:
      VALKEY_EXTRA_FLAGS: "--save 60 1 --loglevel warning"
      # VALKEY_PASSWORD: "valkey"
    volumes:
      - valkeydata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: refract-clickhouse-server
    env_file:
      - .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE_NAME:-refract}
    volumes:
      - ch_data:/var/lib/clickhouse # Persistent data storage
      - ch_logs:/var/log/clickhouse-server # Logs
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
  valkeydata:
  ch_data:
  ch_logs:
